repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^.helm
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: unit_test/static_text.py
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
    - id: flake8
      exclude: unit_test/static_text.py
      args: ["--config=tox.ini", "--tee"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy
      name: mypy-strict
      exclude: '^unit_test'
      args: ["--config-file=tox.ini", "--strict", "--implicit-reexport", "--allow-any-generics"]
      additional_dependencies: [tokenize-rt==3.2.0]
