version: '3'
services:
  steesh:
    build: ./
    container_name: steesh
    environment:
      - STEESH_DEBUG=1
      - HEROKU_APP_NAME=steesh-app
    restart: on-failure
    volumes:
      - ./:/steesh/backend
    ports:
      - "8000:8000"
    command: uvicorn steesh.api.app:app --reload --host 0.0.0.0
    healthcheck:
      test: "curl 0.0.0.0:8000/"
      interval: "10s"
      timeout: "3s"
      start_period: "1s"
      retries: 3
  wait-healthcheck-and-exit:
    image: "alpine:latest"
    depends_on:
      steesh:
        condition: service_healthy
