version: '3'
services:
  steesh:
    build: ./
    container_name: steesh
    environment:
      - FLASK_ENV=development
    restart: on-failure
    volumes:
      - ./:/steesh/backend
    ports:
      - "5000:5000"
    command: python -m steesh.api.app
