name: Verify
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

env:
  PYTHON_ENV_PATH: './env/'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y wkhtmltopdf
          python -m pip install --upgrade pip
      - id: cache-pip
        uses: actions/cache@v1
        continue-on-error: true
        with:
          path: ${{ env.PYTHON_ENV_PATH }}
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m venv ${{ env.PYTHON_ENV_PATH }} && \
            . ${{ env.PYTHON_ENV_PATH }}bin/activate && \
            python -m pip install -r requirements.txt && \
            python -m pip install -r requirements.dev.txt

      - name: Pytest
        run: . ${{ env.PYTHON_ENV_PATH }}bin/activate && python -m pytest
